# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  application:
    name: chat

logging:
  level:
    com.example.*: DEBUG

gcp:
  project-id: "m10lchat-antidote-demo"

thread-pool:
  main:
    prefix: "AsyncClient"
    size:
      core: 100
      max: 100
      queue: 500

perspective:
  uri: "https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key={key}"
  threshold:
    toxicity: 0.75
  key: ${PERSPECTIVE_API_KEY}
